title: "心倾"
author:
  name: "心倾"
description: >
	"这是心倾的Github主页。"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
encoding: UTF-8
domain: lhtxq.github.io
url: https://lhtxq.github.io/
baseurl: /docs/